# ---
# AWSTemplateFormatVersion: 2010-09-09
# Description: CloudFormation - Server Side Encryption

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    NULL:
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
        null:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: { { CRASH } }
      VersioningConfiguration:
        Status: Enabled
        ~:
