name: junit
on:
  pull_request:

jobs:
  build:
    name: Run cfn-guard validate & test with Junit output
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/aws-cloudformation/cloudformation-guard:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run cfn-guard validate with Junit output
        # Replace these paths with your own
        run: /usr/src/cloudformation-guard/cfn-guard validate -r ./path/to/rules/directory_or_file/ -d ./path/to/data/directory_or_file/ --output-format junit --show-summary none --structured > validate-junit.xml || true
      - name: Run cfn-guard test with Junit output
        # Replace these paths with your own
        run: /usr/src/cloudformation-guard/cfn-guard test -r ./path/to/test/directory_or_file/ -t ./path/to/data/directory_or_file/ --output-format junit > test-junit.xml || true
      - name: Publish Validate Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '*.xml'
