---
- input:
    Resources: {}
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: FAIL
      dynamo_db_sse_on: SKIP
      dynamo_db_sse_on_for_prod_only: SKIP
- input:
    Resources: 
      ddb:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          Tags:
            - Key: Normal
              Value: NotSelected
          SSESpecification:
            SSEEnabled: true
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_sse_on: PASS
      dynamo_db_sse_on_for_prod_only: SKIP
- input:
    Resources: 
      ddb:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          Tags:
            - Key: Normal
              Value: NotSelected
          SSESpecification:
            SSEEnabled: true
      ddb2:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          Tags:
            - Key: PROD-DDB
              Value: AppSelected
          SSESpecification:
            SSEEnabled: true
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_sse_on: PASS
      dynamo_db_sse_on_for_prod_only: FAIL
- input:
    Resources: 
      ddb:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          Tags:
            - Key: Normal
              Value: NotSelected
          SSESpecification:
            SSEEnabled: true
      ddb2:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          Tags:
            - Key: PROD-DDB
              Value: AppSelected
          SSESpecification:
            SSEEnabled: true
            SSEType: KMS
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_sse_on: PASS
      # no DeletionPolicy
      dynamo_db_sse_on_for_prod_only: FAIL 
- input:
    Resources: 
      ddb:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          Tags:
            - Key: Normal
              Value: NotSelected
          SSESpecification:
            SSEEnabled: true
      ddb2:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Retain
        Properties:
          Tags:
            - Key: PROD-DDB
              Value: AppSelected
          SSESpecification:
            SSEEnabled: true
            SSEType: KMS
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: PASS
      dynamo_db_sse_on: PASS
      dynamo_db_sse_on_for_prod_only: PASS
- input:
    Resources: 
      ddb:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          # No Tags, will fail 
          SSESpecification:
            SSEEnabled: true
      ddb2:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          Tags:
            - Key: PROD-DDB
              Value: AppSelected
          SSESpecification:
            SSEEnabled: true
            SSEType: KMS
  expectations:
    rules:
      assert_all_resources_have_non_empty_tags: FAIL
      dynamo_db_sse_on: SKIP
      dynamo_db_sse_on_for_prod_only: SKIP
