[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.64"
serde_derive = "1.0.92"
cfn-guard = { version = "3.1.0-beta", path = "../../guard" }
anyhow = "1.0.81"
